### ISSUE TITLE
Crates.io out of date?

### ISSUE THREAD

**Issue by tbelaire** [FranklinChen/rust-tau#1]
The Crates.io version of the package still specifies a #[unstable] annotation, which does not compile on more recent rust versions.  
http://rust-ci.org/FranklinChen/rust-tau/doc/src/tau/lib.rs.html#15

But it looks like the code in this repo is already fixed, you just need to publish to crates.io

**Comment by FranklinChen** [comment]
Actually, the code wasn't really fixed as such, in the sense that in Rust stable, I could not use `PI_2`, which is still unstable. So I just went and cheated and copied the definition right into the source file, since this is really just a crate for fun anyway. If `PI_2` becomes stable eventually, I'll put the old code back.
